#!/usr/bin/with-contenv bash

__wg_conf_target="/config/wg0.conf"




__conf_value=$(cat "$__wg_conf_target")

echo "[WG_PORT_FORWARD] verifying PostUp & PreDown keys"

if echo "$__conf_value" | grep -q 'PreDown\s\+=' && echo "$__conf_value" | grep -q 'PostUp\s\+=' $__wg_conf_target; then
  echo "[WG_PORT_FORWARD] PostUp & PreDown keys were found"
else
  echo "[WG_PORT_FORWARD] pre down command were not found, they will be added"
  __conf_value=$(echo "$__conf_value" | sed 's/\[Interface\]/\[Interface\]\
PostUp = TODO\
PostDown = TODO/' )
fi

echo "$__conf_value"

echo "[WG_PORT_FORWARD] reading environment variables & generating configuration"

__post_up_template="iptables -A INPUT -i wg0 -p udp --dport {{}} -j ACCEPT; iptables -A INPUT -i wg0 -p tcp --dport {{}} -j ACCEPT;"
__post_up_value=""
__pre_down_template="iptables -D INPUT -i wg0 -p udp --dport {{}} -j ACCEPT; iptables -D INPUT -i wg0 -p tcp --dport {{}} -j ACCEPT;"
__pre_down_value=""

while IFS= read -r line; do
  __env_value=${line#*=}
  __env_name=${line%%=*}
  if [[ "$__env_name" =~ ^WG_FORWARDED_PORT_([0-9]+)$ ]]; then
    __forward_number=${BASH_REMATCH[1]}
    __port_number=$__env_value
    echo "[WG_PORT_FORWARD] adding forward number $__forward_number for port $__port_number"
    __post_up_value="$__post_up_value"$( echo $__post_up_template | sed "s/{{}}/$__port_number/g" )
    __pre_down_value="$__pre_down_value"$( echo $__pre_down_template | sed "s/{{}}/$__port_number/g" )
  fi
done < <(env)

if [ "$__post_up_value" = "" ]; then
    echo "[WG_PORT_FORWARD] no forwarded ports found, exiting"
    exit 78
fi

__conf_value=$(echo "$__conf_value" | sed "/^PostUp /s/=.*$/= $__post_up_value/;/^PreDown /s/=.*$/= $__pre_down_value/")

if [ "${WG_PORT_FORWARD_DRYRUN,,}" = "true" ]; then
    echo "[WG_PORT_FORWARD] dry run mode: writing new conf to stdout"
    echo "$__conf_value"
else
    echo "[WG_PORT_FORWARD] writing new conf back to disk"
    echo "$__conf_value"
fi

cat $__wg_conf_target

echo "[WG_PORT_FORWARD] done"
exit 0