#!/usr/bin/with-contenv bash

__wg_conf_target="/config/wg0.conf"

echo "[WG_PORT_FORWARD] checking for wg0.conf"

if [ ! -d "$__wg_conf_target" ]; then
    echo "[WG_PORT_FORWARD] could not find wg0.conf, exiting"
    return 130
fi

echo "[WG_PORT_FORWARD] updating wg0.conf"

cat $__wg_conf_target

echo "[WG_PORT_FORWARD] done"