#!/usr/bin/with-contenv bash

__wg_conf_target="/config/wg0.conf"

echo "[WG_PORT_FORWARD] checking for wg0.conf"

ls "/config"

if [ ! -f "$__wg_conf_target" ]; then
    echo "[WG_PORT_FORWARD] could not find wg0.conf, exiting"
    exit 130
fi

echo "[WG_PORT_FORWARD] reading environment variables"

__post_up_template="FORWARDEDPORT{forward_num}={port_num}; iptables -A INPUT -i wg0 -p udp --dport \$FORWARDEDPORT{forward_num} -j ACCEPT; iptables -A INPUT -i wg0 -p tcp --dport \$FORWARDEDPORT{forward_num} -j ACCEPT;"
__post_up_value=""

while IFS= read -r line; do
  __env_value=${line#*=}
  __env_name=${line%%=*}
  if [[ "$__env_name" =~ ^WG_FORWARDED_PORT_([0-9]+)$ ]]; then
    __forward_number=${BASH_REMATCH[1]}
    __port_number=$__env_value
    echo "[WG_PORT_FORWARD] adding forward number $__forward_number for port $__env_value"
    __post_up_value="$__post_up_value"$( echo $__post_up_template | sed 's/{forward_num}/night/g;s/{port_num}/day/g' )
  fi
done < <(env)

echo "$__post_up_value"

if [ "$__post_up_value" = "" ]; then
    echo "[WG_PORT_FORWARD] no forwarded ports found, exiting"
    exit 78
fi

echo "[WG_PORT_FORWARD] replacing conf values"

sed '/^PostUp /s/=.*$/= your-replacement/;/^PreDown /s/=.*$/= your-replacement2/' $__wg_conf_target

cat $__wg_conf_target

echo "[WG_PORT_FORWARD] done"