name: Build Image

on: [push, pull_request, workflow_dispatch]

env:
  ENDPOINT: "master-hax/wg-port-forward-mod"
  BRANCH: "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.3

      - name: Build image
        run: |
          docker build --no-cache -t ${{ github.sha }} .

      - name: Tag image
        if: ${{ github.ref == format('refs/heads/{0}', env.BRANCH) && env.ENDPOINT != 'user/endpoint' }}
        run: |
          docker tag ${{ github.sha }} ${ENDPOINT}
          docker tag ${{ github.sha }} ${ENDPOINT}:${{ github.sha }}
          docker tag ${{ github.sha }} ghcr.io/${ENDPOINT}
          docker tag ${{ github.sha }} ghcr.io/${ENDPOINT}:${{ github.sha }}

      - name: Credential check
        if: ${{ github.ref == format('refs/heads/{0}', env.BRANCH) && env.ENDPOINT != 'user/endpoint' }}
        run: |
          echo "CR_USER=${{ secrets.CR_USER }}" >> $GITHUB_ENV
          echo "CR_PAT=${{ secrets.CR_PAT }}" >> $GITHUB_ENV
          if [[ "${{ secrets.CR_USER }}" == "" && "${{ secrets.CR_PAT }}" == "" ]]; then
            echo "::error::Push credential secrets missing."
            echo "::error::You must set CR_USER & CR_PAT as secrets in your repo settings."
            echo "::error::See https://github.com/linuxserver/docker-mods/blob/master/README.md for more information/instructions."
            exit 1
          fi

      - name: Login to GitHub Container Registry
        if: ${{ github.ref == format('refs/heads/{0}', env.BRANCH) && env.CR_USER && env.CR_PAT && env.ENDPOINT != 'user/endpoint' }}
        run: |
          echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u ${{ secrets.CR_USER }} --password-stdin

      - name: Push tags to GitHub Container Registry
        if: ${{ github.ref == format('refs/heads/{0}', env.BRANCH) && env.CR_USER && env.CR_PAT && env.ENDPOINT != 'user/endpoint' }}
        run: |
          docker push ghcr.io/${ENDPOINT}:${{ github.sha }}
          docker push ghcr.io/${ENDPOINT}
